### ISSUE TITLE
Navigation bar setup

### ISSUE THREAD

**Issue by Bodhisattwa13** [thesaikatparua/Flim-Fiesta#41]
Hii @thesaikatparua  ,

Please review and solve the bug.

Issues:-
1.Header conflict solution.
2.Routing.

![Screenshot 2024-04-07 000109](https://github.com/thesaikatparua/Flim-Fiesta/assets/155517257/f3a405a8-6d7f-4ebc-998d-48f345ece86f)

cc: @Subhratanu @Debduttaa

**Comment by thesaikatparua** [comment]
Hi @Bodhisattwa13, the problem is fixed.
Thanks.

**Comment by Bodhisattwa13** [comment]
Reviewed and Approved.
Thanks.
