### ISSUE TITLE
Seat booking modification

### ISSUE THREAD

**Issue by Bodhisattwa13** [thesaikatparua/Flim-Fiesta#55]
Hii @Debduttaa  @Subhratanu ,

Please review and solve the bug.

Issues:-
1.Booking seat is not display properly.
2.Users cannot book the seats. 

Ref:
![WhatsApp Image 2024-04-24 at 23 23 30_c6145143](https://github.com/thesaikatparua/Flim-Fiesta/assets/155517257/5a2b475c-5ab0-49b9-b73a-b0ea9db94bdd)

cc: @thesaikatparua

**Comment by Debduttaa** [comment]
Hi @Bodhisattwa13 ,

1.Seatbooking area's problem is fixed

Thanks.

**Comment by Bodhisattwa13** [comment]
Approved
Thank You

**Comment by Bodhisattwa13** [comment]
Approved and new pr added
